#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds000105-fmriprep
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/.reproman/jobs/local/20220420-004319-55a4/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/.reproman/jobs/local/20220420-004319-55a4/stderr

#SBATCH --nodes=2
#SBATCH --ntasks=6
#SBATCH --time=48:00:00
#SBATCH --partition=small

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds000105-fmriprep/.reproman/jobs/local/20220420-004319-55a4

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 5); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun